name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'  # runs daily at 04:15 UTC
  workflow_dispatch:      # allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a daily commit by 22f2000273@ds.study.iitm.ac.in
        run: |
          echo "Daily log: $(date)" >> daily-log.txt
          git config --global user.name "Daily Commit Bot"
          git config --global user.email "22f2000273@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
